title: Filip Janev
description: Creative Editor & Junior Media Buyer — I create, polish, and launch content that performs.
# Option A (current): jekyll-theme-minimal
theme: jekyll-theme-cayman
logo: headshot.jpg

# If you prefer a bolder look, switch to:
# theme: jekyll-theme-cayman

# Add this to allow a custom stylesheet:
plugins:
  - jekyll-seo-tag
